- formats/instance_io_user.ksy
- formats/nav_parent.ksy
- formats/nav_root.ksy
- formats/position_abs.ksy
- formats/position_in_seq.ksy
These 5 unit tests have a naming conflict in C#, the fix mentioned in kaitai-io/kaitai_struct_compiler#2 was to rename the tests for now. I've appended `_obj` onto the conflicting class names to fix the issue. I don't think any unit tests need to change because they shouldn't refer to the class by name.
> Change test cases to avoid name conflicts in C#

- config
- run-csharp
Similar to the `run-java` script, but for C#. Should resolve kaitai-io/kaitai_struct#6. Tested in Bash on Windows - I don't do a lot of Bash scripting so please check it's okay!
There's a few things to note:
- `msbuild`/`xbuild` should be used the build the project/solution, because it can contain commands aside from just the compile step (such as copying files)
- `xbuild` doesn't like when a file is missing, so I'm just clearing the contents of the file instead
- Invalid files are found by running `mcs` and scanning stderr for the files that contain errors
- Once .NET Core has been changed to work with `.csproj` files ([Q1 2017](https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/)) it might be a good idea to switch from Mono to .NET Core for the build
The output of `mcs` …
> Partial compilation script for C#

- spec/php/RepeatUntilS4Test.php
- spec/php/phpunit.xml
The file RepeatUntilS4.php has the following line:
```php
$this->afterall = $this->_io->readStrz("ASCII", 0, false, true, true);
```
it should be changed to the:
```php
$this->afterall = $this->_io->readStrz("ASCII", "\x00", false, true, true);
```
The 0 is integer, but actual byte's value will be a character with the ASCII code 0, not an integer. The character with the code 0 can be encoded as string "\x00" in PHP.
Of course I could add a check and conversion to the character from the ASCII code:
```php
if (is_int($terminator)) {
$terminator = chr($terminator);
}
```
But would it make a sense? I don't think that this is required as the bytes represented as hex strings in PHP.
> Fixed the RepeatUntilS4Test

- spec/php/BufferedStructTest.php
Contents of the BufferedStruct for this test:
```php
namespace Kaitai\Struct\Tests;
class BufferedStruct extends \Kaitai\Struct\Struct {
protected $len1;
protected $_raw_block1;
protected $block1;
protected $len2;
protected $_raw_block2;
protected $block2;
protected $finisher;
public function __construct(\Kaitai\Struct\Stream $io, \Kaitai\Struct\Struct $parent = null, BufferedStruct $root = null) {
parent::__construct($io, $parent, $root);
$this->_parse();
}
public function len1() { return $this->len1; }
public function block1() { return $this->block1; }
public function len2() { return $this->len2; }
public function block2() { return $this->block2; }
public function finisher() { return $this->finisher; }
public function _raw_block1() { return $this->_raw_block1; }
public function …
```
> Fixed BufferedStructTest

- spec/php/Enum0Test.php
- spec/php/Expr0Test.php
- spec/php/Expr1Test.php
Enum0:
```php
<?php
// This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild
namespace Kaitai\Struct\Tests;
class Enum0 extends \Kaitai\Struct\Struct {
public function __construct(\Kaitai\Struct\Stream $io, \Kaitai\Struct\Struct $parent = null, Enum0 $root = null) {
parent::__construct($io, $parent, $root);
$this->_parse();
}
private function _parse() {
self::$Animal = new Enum0\Animal;
$this->pet1 = $this->_io->readU4le();
$this->pet2 = $this->_io->readU4le();
}
protected $pet1;
protected $pet2;
protected static $Animal;
public function pet1() { return $this->pet1; }
public function pet2() { return $this->pet2; }
public static function Animal() {
return self::$Animal;
}
}
namespace Kaitai\Struct\Tests\Enum0;
class Animal {
const DOG = 4;
const …
```
> Fixed Enum0Test, Expr0Test, Expr1Test

- spec/ruby/opaque_external_type_02_parent_spec.rb
I broke `spec_translate_missing` with my indentation by accident.
> https://github.com/kaitai-io/kaitai_struct_compiler/pull/45

- run-javascript
- run-ruby
Some improvements to be able to use the run-scripts under Windows in Git Bash without modifications. One is for JavaScript because node.js uses `;` instead of `:` as dir delimiter and the other for Ruby, if this is installed in a path containing spaces. Under Git Bash, not the `.bat` file for `rspec` is used by default, but the Posix like one which does contain a shebang like the following:
> #!"C:/Program Files (x86)/Ruby23/bin/ruby.exe"
This isn't executed properly, even though Ruby generates this file on its own. Using the `.bat` file instead running the script works.
> https://github.com/kaitai-io/kaitai_struct_tests/issues/18

- formats/switch_multi_bool_ops.ksy
- spec/ruby/switch_multi_bool_ops_spec.rb
In case of multiple boolean operations as condition of a switch statement, parenthesis weren't properly generated. This at least in Java created code which didn't compile.
https://github.com/kaitai-io/kaitai_struct_compiler/issues/39
> #39: Invalid "switch"-statement generated for Java.

- formats/enum_of_value_inst.ksy
- spec/ruby/enum_of_value_inst_spec.rb
I made a mistake in my KSY file, mapping a `value` instance already containing `enum` instances in a boolean operation/`Ast.expr.IfExp` to an `enum`: I used the keyword `enum` in this case, because I somehow thought that I need to provide the resulting data type for the value instance and that didn't work, because KS mapped the expression to `EnumById`. But there was no ID to map of course... I simply needed to not use the `enum` keyword in this case, but it took me quite some time to understand this.
I've added this test to make the difference easier to remember for me or simply have some example I can search for next time. Maybe you find it a bit useful for others and hope you're are merging it.
> Added a test to map value instances to an enum.

- formats/parent_vs_value_inst.ksy
- spec/ruby/parent_vs_value_inst_spec.rb
This is a corresponding test, which should fail during `build-formats` already or simply work.
> #38: Test wrong derivation of _parent in value instances

- formats/bits_simple.ksy
- spec/cpp_stl/test_bits_simple.cpp
add testcase for reading
bitfields with size between 32 bit and 64 bit
At the moment this testcases fail for cpp_stl
> add testcase for testing bitfield-sizes between 32 bit and 64 bit

- formats/enum_to_i_class_border_1.ksy
- formats/enum_to_i_class_border_2.ksy
- spec/ruby/enum_to_i_class_border_1_spec.rb
This adds a test reproducing the problem I encountered in https://github.com/kaitai-io/kaitai_struct/issues/552 in Ruby. Manually changing the generated Ruby makes the test succeed as well, that is where the compiler comes into play.
> Adding some test for issue #552.

- aggregate/convert_to_json
- aggregate/junit_xml_parser.rb
- ci-nim
- config
- run-nim
- run-nim_generate_suite
- spec/nim/generate_test_suite.nim
- spec/nim/tdefault_big_endian.nim
- spec/nim/tests/tdefault_big_endian.nim
`ci-nim` produces a correct `ci.json` in `$TEST_OUT_DIR/nim`.
This PR goes together with [this one](https://github.com/kaitai-io/kaitai_struct_compiler/pull/170).
Can we merge both so I can proceed with setting up Nim for Travis in [ci_targets repo](https://github.com/kaitai-io/ci_targets)?
> Nim is ready for CI

- formats/eos_exception_bytes.ksy
- formats/eos_exception_u4.ksy
- spec/cpp_stl_11/test_eos_exception_bytes.cpp
- spec/cpp_stl_11/test_eos_exception_u4.cpp
- spec/cpp_stl_98/test_eos_exception_bytes.cpp
- spec/cpp_stl_98/test_eos_exception_u4.cpp
- spec/csharp/kaitai_struct_csharp_tests/tests/SpecEosExceptionBytes.cs
- spec/csharp/kaitai_struct_csharp_tests/tests/SpecEosExceptionU4.cs
- spec/java/src/io/kaitai/struct/spec/TestEosExceptionBytes.java
- spec/java/src/io/kaitai/struct/spec/TestEosExceptionU4.java
- spec/javascript/test_eos_exception_bytes.js
- spec/javascript/test_eos_exception_u4.js
- spec/lua/test_eos_exception_bytes.lua
- spec/lua/test_eos_exception_u4.lua
- spec/perl/TestEosExceptionBytes.t
- spec/perl/TestEosExceptionU4.t
- spec/php/EosExceptionBytesTest.php
- spec/php/EosExceptionU4Test.php
- spec/python/test_eos_exception_bytes.py
- spec/python/test_eos_exception_u4.py
- spec/ruby/eos_exception_bytes_spec.rb
- spec/ruby/eos_exception_u4_spec.rb
I noticed that the JavaScript runtime does not throw an exception when trying to read beyond the end of substream, it just passes. This behavior can cause some errors which are hard to find.
So why not test it in all languages?
> Add tests for EOS exceptions

- builder/java_builder.rb
During testing updated PRs https://github.com/kaitai-io/kaitai_struct_compiler/pull/160 and https://github.com/kaitai-io/kaitai_struct_tests/pull/51 I recognized build errors related to hard-coded command lines and stuff like that. Changed that to OS-abstraction provided by ruby and the tests execute now.
Various things needed to be changed:
* ":" -> ";" using FIlE::PATH_SEPERATOR
* "/" -> "\" using File.join because some paths simply got misinterpreted at some places
* quoting paths in "src_list.txt" to support paths containing spaces, as some printed paths were absolute and contain those for me.
While some tests till fail, I don't think this has to do with my changes:
===============================================
Kaitai Struct Java specs
Total tests run: 167, Failures: 2, Skips: 0 …
> Make the builder more compatible with Windows.

- aggregate/junit_xml_parser.rb
currently ci-lua produces invalid bytes under some tests, and reports do not get parsed.
this fixes the issue by replacing the incorrect UTF-8 byte sequences by `?` chars
since those are only in test outputs, it should be acceptable
> fixed reading junit xml reports with invalid UTF-8 sequences

- ci-go
I'm using the MSYS2 terminal (more specifically, [Git Bash for Windows](https://gitforwindows.org/#bash)) for development, which is a Bash shell emulator. The problem is that when using Go for Windows, [the `GOPATH` environment variable](https://golang.org/doc/gopath_code.html#GOPATH) must be a Windows-like path (not `/c/kaitai_struct/tests/`, but `C:/kaitai_struct/tests/`). In the MSYS2 terminal I use, the output of `pwd --help` command hints me that I can use `-W` option to get the Windows physical directory rather than the virtual unix-like path. Here's the output:
```
$ pwd --help
pwd: pwd [-LPW]
Print the name of the current working directory.
Options:
-L        print the value of $PWD if it names the current working
directory
-P        print the physical directory, without any …
```
> Adjust ./ci-go to work on Windows, make various improvements

- .gitignore
- formats_err/attr_bad_key.ksy
- formats_err/expr_unbalanced.ksy
- formats_err/meta_bad_key.ksy
- formats_err/params_call_short_malformed.ksy
- formats_err/repeat_incompatible1.ksy
- formats_err/repeat_incompatible3.ksy
- formats_err/repeat_wo_repeat.ksy
- formats_err/switch_cases_malformed_quoting.ksy
It seems that tests not updated synchronously with compiler updates and now some of them broken. This PR fixes some of them.
Additionally I add commit to ignore rust artifacts, generated by rls in VSCode
> Fix some broken tests

- helpers/javascript/CustomFxNoArgs.js
- helpers/javascript/MyCustomFx.js
- helpers/javascript/nested-deeply/CustomFx.js
- helpers/javascript/testHelper.js
- helpers/javascript/testHelperStream.js
- helpers/javascript/testHelperThrows.js
See https://github.com/kaitai-io/kaitai_struct/issues/1074
This is to adapt to the KSC changes from https://github.com/kaitai-io/kaitai_struct_compiler/pull/264. Therefore, this PR is marked as draft until the compiler PR is merged.
> Adapt to JS generated code exporting an object (not a function)

- formats_err/expr_bytes_to_s_arg0.ksy
- formats_err/expr_bytes_to_s_arg2.ksy
- formats_err/expr_bytes_to_s_type.ksy
PR https://github.com/kaitai-io/kaitai_struct_compiler/pull/269 changes the error text, but tests was note updated. This PR fixes the tests.
Fixes
```
[info] - expr_bytes_to_s_arg0 *** FAILED ***
[info]   expr_bytes_to_s_arg0.ksy: /instances/bad/value:
[info]   	error: wrong arguments to method call `to_s` on byte array: expected (string), got ()
[info]    did not equal expr_bytes_to_s_arg0.ksy: /instances/bad/value:
[info]   	error: to_s: expected 1 argument, got 0 (SimpleMatchers.scala:34)
[info] - expr_bytes_to_s_arg2 *** FAILED ***
[info]   expr_bytes_to_s_arg2.ksy: /instances/bad/value:
[info]   	error: wrong arguments to method call `to_s` on byte array: expected (string), got (Str(foo), Str(bar))
[info]    did not equal expr_bytes_to_s_arg2.ksy: /instances/bad/value:
[info] …
```
> Fix failed tests after compiler PR #269

- formats_err/encoding_str_warnings.ksy
Order was stabilized in https://github.com/kaitai-io/kaitai_struct_compiler/commit/5f561e194f40cf40942615bb5c63a2edfbd348ec
Fixes the following error:
```
[info] - encoding_str_warnings *** FAILED ***
[info]   encoding_str_warnings.ksy: /seq/1/encoding:
[info]   	warning: use canonical encoding name `UTF-8` instead of `utF-8` (see https://doc.kaitai.io/ksy_style_guide.html#encoding-name)
[info]   
[info]   encoding_str_warnings.ksy: /seq/2/encoding:
[info]   	warning: use canonical encoding name `ISO-8859-1` instead of `latin1` (see https://doc.kaitai.io/ksy_style_guide.html#encoding-name)
[info]   
[info]   encoding_str_warnings.ksy: /instances/alias/encoding:
[info]   	warning: use canonical encoding name `ISO-8859-1` instead of `ISo8859-1` (see …
```
> Fix order of expected warnings that was stabilized in compiler

- formats_err/enum_ref_unknown.ksy
- formats_err/expr_inst_value_broken.ksy
- formats_err/expr_unbalanced.ksy
- formats_err/expr_wrong_and.ksy
- formats_err/meta_imports_abs_unknown.ksy
- formats_err/meta_no_id.ksy
- formats_err/params_call_malformed.ksy
- formats_err/params_def_unknown_type.ksy
- formats_err/switch_cases_array.ksy
- formats_err/switch_cases_invalid.ksy
- formats_err/switch_cases_malformed_quoting.ksy
- formats_err/switch_invalid_key.ksy
- formats_err/switch_no_cases.ksy
- formats_err/switch_no_switch_on.ksy
- formats_err/switch_on_malformed.ksy
- formats_err/type_unknown.ksy
After this change all paths in errors will point to existing nodes in KSY file and node, where error is originated
This PR should be merged together with https://github.com/kaitai-io/kaitai_struct_compiler/pull/229 where actual fix done
> Normalize node paths in errors (for compiler#229)

- aggregate/boost_test_parser.rb
- aggregate/convert_to_json
- builder/cpp_builder.rb
- builder/partial_builder.rb
- builder/spec/cpp/boost_aborted_gcc/test_out/cpp_stl_11/results.xml
- builder/spec/cpp/boost_aborted_msvc/test_out/cpp_stl_11/results.xml
- builder/spec/cpp/cpp_builder_spec.rb
- ci-cpp_stl
- valgrind-cpp_stl
Currently, when a single C++ test aborts at runtime (typically due to a `memory access violation`), the entire test suite is terminated. See [Class `test_observer` > `test_aborted()`](https://www.boost.org/doc/libs/1_84_0/libs/test/doc/html/boost/unit_test/test_observer.html#idm46380-bb):
> Called when a critical error is detected.
>
> The critical errors are mainly the signals sent by the system and caught by the Boost.Test framework. Since the running binary may be in incoherent/instable state, the test execution is aborted and all remaining tests are discarded.
This PR allows the CI to recover from that by detecting the aborted test and running the test executable again excluding the previously aborted tests (using the `--run_test=!<absolute_spec>` option, see [Test unit filtering > …
> C++/STL: recover from aborted tests

- formats_err/type_unknown_many.ksy
Fixes the test
```
[info] - type_unknown_many *** FAILED ***
[info]   type_unknown_many.ksy: /seq/0/type:
[info]   	error: unable to find type 'some_unknown_name', searching from type_unknown_many
[info]
[info]   type_unknown_many.ksy: /seq/1/type:
[info]   	error: unable to find type 'also_unknown_name', searching from type_unknown_many
[info]
[info]   type_unknown_many.ksy: /seq/2/enum:
[info]   	error: unable to find enum 'unknown_enum', searching from type_unknown_many
[info]    did not equal type_unknown_many.ksy: /seq/0:
[info]   	error: unable to find type 'some_unknown_name', searching from type_unknown_many
[info]
[info]   type_unknown_many.ksy: /seq/1:
[info]   	error: unable to find type 'also_unknown_name', searching from type_unknown_many
[info]
[info] …
```
> Adjust one more test that was forgotten to update after rebase of #92

- formats_err/meta_imports_rel2.ksy
- formats_err/meta_imports_rel_unknown.ksy
This PR
- fixes paths in errors that was changed in https://github.com/kaitai-io/kaitai_struct_compiler/commit/2851d203be30d2e66e5d4f3b9499355c94cc415a
- add a `.ksy` suffix to the file names which is implemented in https://github.com/kaitai-io/kaitai_struct_compiler/pull/285
> Use filename instead of name

- translator/src/main/scala/io/kaitai/struct/testtranslator/specgenerators/LuaSG.scala
- translator/src/main/scala/io/kaitai/struct/testtranslator/specgenerators/PythonSG.scala
If it is used in `simpleEquality`, then it should be used in `floatEquality` as well
> Lua, Python: use special translation method for expected value of float checks as well

- translator/src/main/scala/io/kaitai/struct/testtranslator/Main.scala
The Go translator is not included into `all` category since https://github.com/kaitai-io/kaitai_struct_tests/commit/0590480901f6074350800bd3b87b7420182b6cd7, which is strange. It's implementation not worse that, for example, Construct translator and it actually have more high rating on https://ci.kaitai.io.
> Revert "Translator: allow go, but not by default" - Go translator is no worse than others
